from .user_dao import UserDAO
from .manufacturer_dao import ManufacturerDAO
from .equipment_dao import EquipmentDAO
from .spare_part_dao import SparePartDAO
from .technician_dao import TechnicianDAO
from .repair_type_dao import RepairTypeDAO
from .user_equipment_dao import UserEquipmentDAO
from .repair_dao import RepairDAO
from .replaced_part_dao import ReplacedPartDAO
from .technician_schedule_dao import TechnicianScheduleDAO
from .technician_repairs_dao import TechnicianRepairsDAO