from .user_controller import user_bp
from .manufacturer_controller import manufacturer_bp
from .equipment_controller import equipment_bp
from .spare_part_controller import spare_part_bp
from .technician_controller import technician_bp
from .repair_type_controller import repair_type_bp
from .user_equipment_controller import user_equipment_bp
from .repair_controller import repair_bp
from .replaced_part_controller import replaced_part_bp
from .technician_schedule_controller import technician_schedule_bp
